'use strict';
const $=id=>document.getElementById(id),ctx=$('overlayCanvas').getContext('2d');
const base='./';
let data,records=[],stage='rollout',frame=41,family='all',playing=false,last=0,ticket=0;
const cache=new Map(),colors={A:'#42df91',B:'#37aef5',C:'#ffae47',D:'#ff514c'};
const names={A:'A · Oracle / zero omega',B:'B · State + radius error',C:'C · Geometry',D:'D · End-to-end'};
const selectedArms=r=>({A:r.abcd.A,B:r.abcd.B,C:r.abcd[$('cMode').value],D:r.abcd.D});
const titles={context:'Context RGB',mask:'Grounding DINO + SAM2',state:'State p7 / v7',depth:'VGGT depth',geometry:'Observed finite mesh',rollout:'Bullet rollout'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v==null?'NOT_RUN':Number(v).toFixed(3),metric=(k,v)=>`<div class="metric-row"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`;
const limit=()=>stage==='rollout'?41:stage==='geometry'?0:7;
function list(){const rows=records.filter(r=>(family==='all'||r.family===family)&&r.case_id.includes($('caseSearch').value));$('visibleCaseCount').textContent=rows.length;$('caseList').innerHTML=rows.map(r=>`<button class="case-row ${r===data?'is-active':''}" data-case="${r.id}" role="option"><strong>${esc(r.case_id.replace('phase1_',''))}</strong><span class="case-ade">${r.trajectory_metrics?fmt(r.trajectory_metrics.ADE_m)+'m':'FAIL'}</span><small>${r.family}</small><small>${r.rollout_status==='EXECUTED'?'41帧已完成':'状态失败 · 未推进'}</small></button>`).join('')}
async function image(url){if(!cache.has(url))cache.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error(url));im.src=url}));return cache.get(url)}
function line(points,color,width=2){if(!points)return;ctx.beginPath();let first=true;for(const p of points){if(!p||!p.every(Number.isFinite)){first=true;continue}if(first){ctx.moveTo(...p);first=false}else ctx.lineTo(...p)}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
async function load(id){data=records.find(r=>r.id===id);playing=false;$('caseTitle').textContent=data.case_id.replace('phase1_','');$('familyBadge').textContent=data.family;$('variantText').textContent=data.rollout_status;list();frame=stage==='rollout'?41:0;await draw()}
async function selectStage(s){stage=s;frame=s==='rollout'?41:0;playing=false;await draw()}
async function draw(){if(!data)return;const token=++ticket,r=data,t=Math.min(frame,7);$('loadingOverlay').hidden=false;
 const url=stage==='depth'?`${base}diagnostics/${r.id}/depth_${t}.png`:`${base}inputs/${r.id}/rgb_${String(['rollout','geometry'].includes(stage)?7:t).padStart(2,'0')}.png`;
 try{const im=await image(url);if(token!==ticket)return;ctx.clearRect(0,0,640,360);ctx.drawImage(im,0,0,640,360);
 if(stage==='mask'){r.mask_contours[t].forEach(c=>line(c.concat([c[0]]),'#37aef5'));if(t===7){const b=r.target_detection.candidates[0].box;ctx.strokeStyle='#ffdc32';ctx.strokeRect(b[0],b[1],b[2]-b[0],b[3]-b[1])}}
 if(stage==='state'&&r.center_uv){line(r.center_uv.slice(0,t+1),'#ffdc32');for(const p of r.center_uv.slice(0,t+1)){ctx.beginPath();ctx.arc(...p,3,0,Math.PI*2);ctx.strokeStyle='#ffdc32';ctx.stroke()}}
 let keys=[];if(stage==='rollout'){for(const [k,m]of Object.entries(selectedArms(r))){if(document.querySelector(`[data-layer="${k}"]`).checked){const label=names[k]+(k==='C'?' · '+$('cMode').value:'');if(m.points_px.length){const path=m.points_px.slice(0,frame+1);line(path,'#111',4);line(path,colors[k]);const point=path[path.length-1];if(point?.every(Number.isFinite)){ctx.beginPath();ctx.arc(...point,m.radius_px[frame],0,Math.PI*2);ctx.strokeStyle=colors[k];ctx.stroke()}keys.push([label,colors[k]])}else keys.push([label+' · BLOCKED',colors[k]])}}}
 if(['rollout','geometry'].includes(stage)&&document.querySelector('[data-layer="estimatedGeometry"]')?.checked){for(const segment of r.mesh_boundary_segments_uv||[])line(segment,'#f453dc',1);keys.push(['Estimated geometry','#f453dc']);for(const segment of r.inferred_mesh_segments_uv||[])line(segment,'#ffdd44',1);if(r.inferred_mesh_segments_uv?.length)keys.push(['Inferred plane · 推断补全','#ffdd44'])}
 if(['rollout','geometry'].includes(stage)&&document.querySelector('[data-layer="gtGeometry"]')?.checked){for(const segment of r.gt_geometry_segments_uv||[])line(segment,'#42df91',1);keys.push(['GT geometry · eval only','#42df91'])}
 $('canvasKey').innerHTML=keys.map(([n,c])=>`<span class="key-item"><i class="key-dot" style="color:${c}"></i>${esc(n)}</span>`).join('');$('loadingOverlay').hidden=true;
 }catch(e){$('loadingOverlay').textContent='加载失败 '+e.message;throw e}
 $('timeline').max=limit();$('timeline').value=frame;$('timeline').disabled=stage==='geometry';$('frameBadge').textContent=`RGB${stage==='rollout'?frame+7:stage==='geometry'?0:frame}${stage==='rollout'?' · RGB7 HOLD':''}`;$('timeOutput').textContent=(stage==='rollout'?'+':'')+fmt(frame/30)+' s';$('playPause').textContent=playing?'Ⅱ':'▶';
 document.querySelectorAll('[data-stage]').forEach(b=>b.classList.toggle('is-active',b.dataset.stage===stage));$('layerControls').hidden=!['rollout','geometry'].includes(stage);$('inspectorStep').textContent=titles[stage];$('stageStatus').textContent=stage==='rollout'?'EVALUATED':stage==='state'?r.state_status:'OBSERVED';
 $('scopeBadge').textContent=stage==='rollout'?'EVALUATION':'ESTIMATOR';let rows='',note='';
 if(stage==='context'){rows=metric('输入','RGB0–7 + 时间戳')+metric('目标短语',r.target_detection.prompt);note='固定相机单球实验；不使用未来输入。'}
 if(stage==='mask'){rows=metric('定位','Grounding DINO RGB7唯一框')+metric('跟踪','SAM2双向传播')+metric('面积',r.mask_contours[t].length+' 个外轮廓');note='蓝色原始mask边界；黄色RGB7提示框。不做圆形轮廓修整。'}
 if(stage==='state'){rows=metric('状态',r.state_status)+metric('半径 (m)',fmt(r.fit_diagnostics.radius))+metric('p7误差 (m)',fmt(r.state_metrics?.p7_error_m))+metric('v7误差 (m/s)',fmt(r.state_metrics?.v7_error_mps))+metric('radius CV',fmt(r.fit_diagnostics.radius_cv))+metric('球面相对RMS',fmt(r.fit_diagnostics.relative_rms));note='未知半径联合拟合；失败拟合仅诊断。'+JSON.stringify(r.fit_diagnostics.reasons)}
 if(stage==='depth'){rows=metric('模型','VGGT')+metric('固定scale','5.819486884015457');note='原始VGGT深度；八帧共享2–98%色域。不是GT校正深度。'}
 if(stage==='geometry'){rows=metric('估计几何','有限mesh；黄色推断面')+metric('GT几何','实际静态box边界，地面不画伪造有限边界')+metric('推断像素',r.completion_audit?.inferred_pixels??0);note='紫色估计边界、黄色补全三角形、绿色GT线框。GT仅用于冻结后的独立对照。'}
 if(stage==='rollout'){for(const [k,m]of Object.entries(r.abcd)){rows+=metric(k+' ADE / FDE',fmt(m.ADE_m)+' / '+fmt(m.FDE_m)+' m')+metric(k+' 状态',m.status)+(m.reason?metric('拒绝原因',m.reason):'')+metric('半径',fmt(m.radius_m)+' m')+metric('初始化',m.initialization.status)+metric('位移',m.initialization.displacement_m.map(x=>fmt(x*1000)).join(', ')+' mm');}note='所有组zero omega，共享估计重力和固定物性。B含估计半径；A不是完整GT重放。严格C与aligned C独立保存；BLOCKED不画轨迹。'}
 $('stageSummary').innerHTML=`<h1>${titles[stage]}</h1><p>${esc(note)}</p><div class="metric-stack">${rows}</div>`;$('boundaryText').textContent='A/B的GT几何、A/C的GT状态只用于冻结后评测。B/D使用估计半径。D与已冻结部署结果逐帧一致。接触是按法向划分的通用角色，不等同于GT语义事件。';$('frameReadout').innerHTML=metric('时间',fmt(frame/30)+' s')+(stage==='rollout'?Object.entries(selectedArms(r)).map(([k,m])=>metric(k+' 该帧误差',frame?fmt(m.position_error_m[frame-1])+' m':'初始化')+metric(k+' 接触',m.contact_outcome)+metric(k+' 新接触时刻',fmt(m.first_new_contact_time_s))+metric(k+' 最大穿透',fmt(m.max_penetration_m))).join(''):'');
}
$('caseList').onclick=e=>{const b=e.target.closest('[data-case]');if(b)load(b.dataset.case)};$('caseSearch').oninput=list;
document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{family=b.dataset.family;document.querySelectorAll('[data-family]').forEach(x=>x.classList.toggle('is-active',x===b));list()});document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>selectStage(b.dataset.stage));document.querySelectorAll('[data-layer]').forEach(b=>b.onchange=draw);
$('timeline').oninput=e=>{frame=+e.target.value;playing=false;draw()};$('previousFrame').onclick=()=>{frame=Math.max(0,frame-1);draw()};$('nextFrame').onclick=()=>{frame=Math.min(limit(),frame+1);draw()};$('playPause').onclick=()=>{playing=!playing;if(playing&&frame===limit())frame=0;draw()};
function tick(now){if(playing&&now-last>1000/+$('playbackFps').value){last=now;frame=(frame+1)%(limit()+1);draw()}requestAnimationFrame(tick)}
$('cMode').onchange=draw;
(async()=>{const d=await(await fetch(base+'viewer_data.json')).json();records=d.records;$('summaryAde').textContent=fmt(d.summary.arms.D.ADE_mean_m)+'m';$('summaryFde').textContent=fmt(d.summary.arms.D.FDE_mean_m)+'m';$('summaryContact').textContent=d.summary.arms.D.status_counts.EXECUTED+'/36';$('summaryContact').nextElementSibling.textContent='D EXECUTED';await load(records[0].id);requestAnimationFrame(tick)})();
