"""Strict-causal xSSC representation audit utilities."""

STATIC_DIM = 384
DYNAMIC_DIM = 128
SLOT_DIM = STATIC_DIM + DYNAMIC_DIM
NUM_SLOTS = 11
NUM_OBJECTS = 10
NUM_RAW_FRAMES = 24
NUM_STATES = 12
LABEL_FRAME_INDICES = tuple(range(1, NUM_RAW_FRAMES, 2))
CALIBRATION_STATES = 4

