"""Ordered metric definitions shown verbatim in the dashboard."""

METRIC_DEFINITIONS = [
    {
        "rank": 1,
        "priority": "P0",
        "id": "gt_center_ade_change",
        "name": "GT Center-ADE Change",
        "definition": "消融相对 simulator GT 的中心轨迹误差，减去 Baseline 的同一误差。",
        "formula": "mean_t ||c_abl(t)-c_GT(t)|| / D0 - mean_t ||c_base(t)-c_GT(t)|| / D0",
        "direction": "0 最好；正值表示物理轨迹变差，负值表示变好",
        "asset": "trajectory",
    },
    {
        "rank": 2,
        "priority": "P0",
        "id": "baseline_center_ade",
        "name": "Baseline-relative Center-ADE",
        "definition": "消融对象中心与同 seed 未消融中心的逐帧距离。",
        "formula": "mean_t ||c_abl(t)-c_base(t)|| / D0",
        "direction": "越大表示可见因果效应越强；不表示物理更差",
        "asset": "trajectory",
    },
    {
        "rank": 3,
        "priority": "P0",
        "id": "gt_velocity_error_change",
        "name": "GT Velocity Error Change",
        "definition": "消融相对 GT 的中心速度向量误差变化，使用四帧差分抑制跟踪抖动。",
        "formula": "v(t)=(c(t+4)-c(t))/4; mean ||v_abl-v_GT|| - mean ||v_base-v_GT||",
        "direction": "正值表示速度物理误差增加",
        "asset": "trajectory",
    },
    {
        "rank": 4,
        "priority": "P0",
        "id": "contact_time_error_change",
        "name": "Contact-time Error Change",
        "definition": "SAM2 mask 连续两帧接触时刻相对 simulator sphere-OBB 接触时刻的误差变化；若候选从未形成持续接触则报告 N/A，不虚构惩罚帧。",
        "formula": "|tau_abl-tau_GT| - |tau_base-tau_GT|",
        "direction": "正值表示接触时刻更差；单位 frame",
        "asset": "mask",
    },
    {
        "rank": 5,
        "priority": "P0",
        "id": "post_contact_velocity_error_change",
        "name": "Post-contact Velocity Error Change",
        "definition": "GT 接触后固定八帧窗口内，消融与 Baseline 相对 GT 的速度向量误差差。",
        "formula": "mean_post ||v_abl-v_GT|| - mean_post ||v_base-v_GT||",
        "direction": "正值表示碰撞后运动更差",
        "asset": "trajectory",
    },
    {
        "rank": 6,
        "priority": "P0",
        "id": "other_object_center_ade",
        "name": "Other-object Center-ADE",
        "definition": "单对象消融后，未被选中对象相对 Baseline 的中心轨迹变化。",
        "formula": "mean_t ||c_other,abl(t)-c_other,base(t)|| / D_other",
        "direction": "越大表示对外传播或 spillover 越强",
        "asset": "trajectory",
    },
    {
        "rank": 7,
        "priority": "P1",
        "id": "center_fde",
        "name": "Center-FDE",
        "definition": "最后共同有效帧的对象中心距离。",
        "formula": "||c_abl(t*)-c_ref(t*)|| / D0, t*=max(common valid frames)",
        "direction": "越低越接近所选 reference",
        "asset": "trajectory",
    },
    {
        "rank": 8,
        "priority": "P1",
        "id": "object_normalized_pck",
        "name": "Object-normalized PCK@5/10/20%",
        "definition": "CoTracker 点到 reference 对应点的距离，小于 F00 bbox 对角线一定比例的占比。",
        "formula": "mean_(i,t) 1[||p_abl-p_ref|| < alpha D0], alpha in {0.05,0.10,0.20}",
        "direction": "越高越接近 reference",
        "asset": "trajectory",
    },
    {
        "rank": 9,
        "priority": "P1",
        "id": "native_pck",
        "name": "Native PCK@16/32/64",
        "definition": "在 1280×704 输出坐标中计算的点轨迹 PCK；不是 Attention Q→K PCK。",
        "formula": "mean_(i,t) 1[||p_abl-p_ref|| < tau], tau in {16,32,64}px",
        "direction": "越高越接近 reference",
        "asset": "trajectory",
    },
    {
        "rank": 10,
        "priority": "P1",
        "id": "point_ade",
        "name": "Point-ADE",
        "definition": "所有共同可见 CoTracker 表面点的平均轨迹距离。",
        "formula": "mean_(i,t) ||p_abl(i,t)-p_ref(i,t)|| / D0",
        "direction": "越低越接近；会包含球体滚动/表面点变化",
        "asset": "trajectory",
    },
    {
        "rank": 11,
        "priority": "P1",
        "id": "velocity_decomposition",
        "name": "Velocity Speed / Direction / Vector Error",
        "definition": "将四帧中心速度误差拆成大小、方向和完整向量误差。",
        "formula": "mean | |v_a|-|v_r| |; mean acos(cos(v_a,v_r)); mean ||v_a-v_r||",
        "direction": "均越低越接近；方向只统计双方非静止帧",
        "asset": "trajectory",
    },
    {
        "rank": 12,
        "priority": "P1",
        "id": "shape_iou",
        "name": "Center-aligned Shape IoU",
        "definition": "仅平移质心对齐 SAM2 mask 后计算 IoU，不做缩放。",
        "formula": "IoU(translate(M_abl, c_ref-c_abl), M_ref)",
        "direction": "越高表示形状越接近",
        "asset": "mask",
    },
    {
        "rank": 13,
        "priority": "P1",
        "id": "shape_geometry",
        "name": "Area / Aspect / Circularity Error",
        "definition": "对象 mask 的面积、bbox 长宽比和 4πA/P² 圆度误差。",
        "formula": "|log(A_a/A_r)|; |log(aspect_a/aspect_r)|; |circ_a-circ_r|",
        "direction": "均越低越接近 reference",
        "asset": "mask",
    },
    {
        "rank": 14,
        "priority": "P1",
        "id": "raft_roi_epe",
        "name": "RAFT ROI Flow EPE",
        "definition": "在所选 reference 冻结的动态 CoTracker ROI 内比较两个视频相邻帧 RAFT flow；Baseline 列用 Baseline ROI，GT 列用 source-render ROI。",
        "formula": "mean_(t,x in ROI) ||u_abl(t,x)-u_ref(t,x)||",
        "direction": "越低越接近；是估计光流 disagreement，不是真实 flow GT",
        "asset": "raft",
    },
    {
        "rank": 15,
        "priority": "P1",
        "id": "raft_motion_ratio",
        "name": "RAFT Motion Magnitude Ratio",
        "definition": "同一冻结 ROI 中消融平均运动幅度相对 reference 的比例。",
        "formula": "mean ||u_abl|| / (mean ||u_ref|| + eps)",
        "direction": "接近 1 仅表示运动量接近；reference 近静止时不稳定",
        "asset": "raft",
    },
    {
        "rank": 16,
        "priority": "P2",
        "id": "object_dino_similarity",
        "name": "Object DINOv2 Similarity",
        "definition": "固定物理 crop 尺寸、质心平移对齐后，对 mask-pooled DINOv2 patch feature 求 cosine。",
        "formula": "mean_t cosine(pool_mask(f_abl), pool_mask(f_ref))",
        "direction": "越高表示对象语义/身份外观越接近",
        "asset": "perceptual",
    },
    {
        "rank": 17,
        "priority": "P2",
        "id": "object_lpips",
        "name": "Object LPIPS",
        "definition": "固定尺寸、质心对齐、mask 外置灰的对象 crop 上计算 LPIPS-Alex。",
        "formula": "mean_t LPIPS(masked_crop_abl, masked_crop_ref)",
        "direction": "越低表示局部外观越接近",
        "asset": "perceptual",
    },
    {
        "rank": 18,
        "priority": "P2",
        "id": "outside_object_lpips",
        "name": "Outside-object LPIPS",
        "definition": "排除两视频对象 mask 膨胀并集后，对剩余区域计算 LPIPS。",
        "formula": "mean_t LPIPS(I_abl * outside, I_ref * outside)",
        "direction": "越低表示背景/非目标区域 spillover 越弱",
        "asset": "pixel",
    },
    {
        "rank": 19,
        "priority": "P2",
        "id": "raw_mask_iou",
        "name": "Raw-mask IoU",
        "definition": "不进行任何对齐的逐帧 SAM2 mask IoU。",
        "formula": "mean_t |M_abl ∩ M_ref| / |M_abl ∪ M_ref|",
        "direction": "越高越接近；同时混合位置与形状变化",
        "asset": "mask",
    },
    {
        "rank": 20,
        "priority": "P3",
        "id": "vbench_subject_consistency",
        "name": "VBench Subject Consistency",
        "definition": "复用每个生成视频 manifest 中的官方 VBench score。",
        "formula": "official VBench per-video score; report score and score_abl-score_base",
        "direction": "越高越一致；冻结视频也可能高分，只作 sanity",
        "asset": "input",
    },
    {
        "rank": 21,
        "priority": "P3",
        "id": "vbench_motion_smoothness",
        "name": "VBench Motion Smoothness",
        "definition": "复用 AMT 插帧一致性定义的 VBench 运动平滑度。",
        "formula": "official VBench score and delta to Baseline",
        "direction": "越高越平滑；不代表运动方向或物理结果正确",
        "asset": "input",
    },
    {
        "rank": 22,
        "priority": "P3",
        "id": "vbench_dynamic_degree",
        "name": "VBench Dynamic Degree",
        "definition": "复用 VBench 对视频是否具有足够运动的判定分数。",
        "formula": "official VBench score and delta to Baseline",
        "direction": "用于识别冻结，不评价物理正确性",
        "asset": "input",
    },
    {
        "rank": 23,
        "priority": "P3",
        "id": "vbench_quality_suite",
        "name": "VBench Background / Flicker / Imaging / Aesthetic",
        "definition": "复用四项官方 VBench 生成质量分数。",
        "formula": "each official score plus ablation-minus-baseline delta",
        "direction": "仅作生成崩坏和视觉质量 sanity",
        "asset": "input",
    },
    {
        "rank": 24,
        "priority": "P3",
        "id": "full_frame_similarity",
        "name": "Full-frame SSIM / PSNR / MAE",
        "definition": "统一缩放后逐帧比较全图并取均值。",
        "formula": "mean SSIM; 10log10(255²/MSE); mean |I_abl-I_ref|/255",
        "direction": "SSIM/PSNR 越高、MAE 越低越相似；静态背景会稀释对象变化",
        "asset": "pixel",
    },
    {
        "rank": 25,
        "priority": "P3",
        "id": "temporal_delta_mae",
        "name": "Temporal Δ-MAE",
        "definition": "比较两个视频相邻帧差分的绝对误差。",
        "formula": "mean |(I_abl(t+1)-I_abl(t))-(I_ref(t+1)-I_ref(t))| / 255",
        "direction": "越低表示逐帧变化模式越接近",
        "asset": "pixel",
    },
]
