from pathlib import Path
import json,html
R=Path('/data/gaoya/agent-data/outputs_v1/geometry_transfer/20261003_test70_multiscene_preview');cfg=json.loads((R/'config.json').read_text());rows=[];cards=[]
for case in json.loads((R/'preview_cases.json').read_text()):
 m=json.loads((R/'cases'/case/'metadata.json').read_text());s=cfg['scene_by_family'][m['family_key']];rows.append(dict(case=case,**s))
 cards.append(f'<article id="{case}"><h2>{html.escape(s["task_label"])}</h2><p>{html.escape(s["label"])} · {html.escape(s["name"])}</p><a class="frame" target="_blank"><span>等待渲染</span></a><small class="state">GPU2 · 第1帧 · 保留原始任务物体</small><details><summary>场景与配置</summary><p>同组5个case使用同一场景。当前仅展示一个代表case。</p><code>{case}</code><p>BlenderKit asset: {s["asset_id"]}</p></details></article>')
(R/'scene_assignments.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
s='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Test70 · 14组独立场景预览</title><style>body{margin:24px;background:#efeee9;color:#243329;font:16px system-ui}main{max-width:1550px;margin:auto}h1{margin-bottom:8px}p{line-height:1.6}#cases{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}article{background:white;border:1px solid #d4d9d2;padding:18px}h2{margin:0;font-size:21px}.frame{display:flex;align-items:center;justify-content:center;aspect-ratio:7/4;background:#25352f;color:white;overflow:hidden}.frame img{display:block;width:100%;height:100%;object-fit:contain}small{display:block;margin-top:10px;color:#53665a}details{margin-top:12px}code{overflow-wrap:anywhere}a{color:#146b63}#status{padding:12px;background:#dfe6de}@media(max-width:800px){#cases{grid-template-columns:1fr}body{margin:12px}}</style><main><h1>14组 · 14个独立场景</h1><p>每组先渲染一张带任务物体的背景预览。同组5个case固定场景，组间改变房间布局、家具、地板与采光。保留各组几何与相对运动。多米诺组放到0.8米高、有桌腿支撑的桌面，并调整构图展示桌子。使用GPU2 / Cycles。</p><p><a href="/test70-photoreal-preview/">上一轮三组完整视频</a> · <a href="scene_assignments.json">场景分配</a> · <a href="config.json">渲染配置</a></p><p id="status">读取进度…</p><div id="cases">CARDS</div><p>背景来自BlenderKit免费Royalty Free场景；仅展示渲染结果，不分发源资产。</p></main><script>
const cases=CASES;const loaded=new Map();
async function refresh(){let state={};try{state=await(await fetch('pipeline_status.json',{cache:'no-store'})).json();}catch(e){}let review={};try{let r=await fetch('visual_review.json',{cache:'no-store'});if(r.ok)review=await r.json();}catch(e){}
await Promise.all(cases.map(async c=>{try{const r=await fetch('cases/'+c+'/preview_complete.json',{cache:'no-store'});if(!r.ok){const el=document.getElementById(c);el.querySelector('.frame').innerHTML='<span>等待本轮预览</span>';el.querySelector('.state').textContent='正在重新渲染';loaded.delete(c);return;}const d=await r.json();const el=document.getElementById(c);if(loaded.get(c)!==d.sha256){let img=new Image();img.alt=el.querySelector('h2').textContent+'背景预览';img.src='cases/'+c+'/calibration_frames/frame_0001.png?v='+d.sha256;await img.decode();let a=el.querySelector('.frame');a.replaceChildren(img);a.href=img.src;loaded.set(c,d.sha256);}let note=review.cases?.find(x=>x.case===c);el.querySelector('.state').textContent=note?.status==='PASS'&&note.image_sha256===d.sha256?'已完成并检查 · GPU2 · 点击放大':'已渲染，待视觉检查 · GPU2 · 点击放大';}catch(e){}}));
const stage={WAITING_GPU2:'等待GPU2',RENDERING:'GPU2正在渲染',RENDERED_PENDING_REVIEW:'渲染完成，正在检查',COMPLETE:'全部预览完成',PARTIAL_FAILURE:'部分场景需要调整'}[state.stage]||state.stage||'准备中';document.querySelector('#status').textContent=`${stage} · ${loaded.size}/14 张 · 每15秒自动更新`;
}refresh();setInterval(refresh,15000);
</script></html>'''
s=s.replace('CARDS',''.join(cards)).replace('CASES',json.dumps([r['case'] for r in rows]));(R/'index.html').write_text(s)
hub=Path('/data/gaoya/agent-data/physv_v2v_0819/visualization/hub');link=hub/'test70-multiscene-preview'
if not link.exists():link.symlink_to(R,target_is_directory=True)
else:assert link.resolve()==R
print('http://10.176.42.45:8844/test70-multiscene-preview/')
