from pathlib import Path
import json
R=Path('/data/gaoya/agent-data/outputs_v1/geometry_transfer/20261003_test70_v2/test70_v2')
groups=json.loads((R/'group_assignments.json').read_text())
html='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Test70 v2 · 完整渲染</title><style>body{margin:24px;background:#f1efe9;color:#263334;font:16px system-ui}header{position:sticky;top:0;background:#f1efe9ee;padding:16px 0;z-index:1}h1{margin:0}button,select{padding:8px;margin:8px 8px 8px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:14px}article{background:white;border:1px solid #d4d8d0;border-radius:8px;padding:12px;overflow-wrap:anywhere}video{width:100%;aspect-ratio:1.75;background:#e1e3dc}.pending{aspect-ratio:1.75;display:grid;place-items:center;background:#e1e3dc}.note{font-size:13px;color:#647168}</style><header><h1>Test70 v2</h1><p id="status">正在读取队列进度…</p><select id="group"><option value="">全部场景组</option></select><button id="replay">全部重新播放</button><span class="note">14 组 × 5 case · GPU2 · 896×512 · 90帧/30fps</span></header><p>使用已确认的写实场景。视频完成后自动加入；每 15 秒刷新进度。几何可见性检查提示会单独列出，完成渲染不代表已人工审核。</p><main id="main"></main><script>
const groups=GROUPS;const cards=new Map();
for(const [family,g] of Object.entries(groups)){const opt=document.createElement('option');opt.value=family;opt.textContent=g.scene.task_label;document.querySelector('#group').append(opt);const section=document.createElement('section');section.dataset.family=family;const title=document.createElement('h2');title.textContent=g.scene.task_label+' · '+g.scene.label;section.append(title);const grid=document.createElement('div');grid.className='grid';for(const c of g.cases){const a=document.createElement('article');const label=document.createElement('strong');label.textContent=c;a.append(label);const body=document.createElement('div');body.className='pending';body.textContent='等待渲染';a.append(body);const note=document.createElement('p');note.className='note';a.append(note);cards.set(c,{body,note,a,ready:false});grid.append(a)}section.append(grid);document.querySelector('#main').append(section)}
document.querySelector('#group').onchange=e=>document.querySelectorAll('section').forEach(s=>s.hidden=!!e.target.value&&s.dataset.family!==e.target.value);
document.querySelector('#replay').onclick=()=>document.querySelectorAll('section:not([hidden]) video').forEach(v=>{v.currentTime=0;v.play().catch(()=>{})});
async function update(){try{const [s,m]=await Promise.all(['reports/pipeline_status.json','manifest.json'].map(u=>fetch(u+'?t='+Date.now()).then(r=>r.json())));let text=`已完成 ${s.completed}/70 · ${s.stage}`;if(s.current){text+=' · '+s.current;try{const p=await fetch('samples/'+s.current+'/render_progress.json?t='+Date.now()).then(r=>r.json());text+=` · ${p.frame}/90 帧`}catch{}}document.querySelector('#status').textContent=text;for(const item of m.samples){const c=cards.get(item.sample_id);if(!c.ready){const v=document.createElement('video');v.controls=true;v.muted=true;v.loop=true;v.preload='none';v.poster='samples/'+item.sample_id+'/frames/00000.png';v.src='samples/'+item.sample_id+'/videos/rgb_cycles.mp4';c.body.replaceWith(v);c.ready=true}c.note.textContent=item.qa_warning_count?'渲染完成 · 几何检查提示 '+item.qa_warning_count+' 项，待复核':'渲染完成 · 自动检查通过 · 待人工审核'}}catch(e){document.querySelector('#status').textContent='等待流水线状态更新'}}update();setInterval(update,15000);
</script></html>'''.replace('GROUPS',json.dumps(groups,ensure_ascii=False))
(R/'index.html').write_text(html)
for link in [Path('/data/gaoya/agent-data/physv_v2v_0819/visualization/hub/test70_v2'),Path('/data/gaoya/AAA_test_video/test70_v2')]:
 if link.is_symlink():assert link.resolve()==R
 else:assert not link.exists();link.symlink_to(R,target_is_directory=True)
print(R/'index.html')
