#!/usr/bin/env python3
"""Prepare the frozen 20-case x five-seed Phase-B/D manifest.

Only frame-zero information from the existing automatic source tubes is copied
into the object-query cache.  Future source trajectories and masks are not used
by generation.  Missing clean baselines are assigned deterministic output paths
and are generated by the next pipeline stage.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import cv2
import imageio.v3 as iio
import numpy as np

from AAA_my_test.sam2_region_query_utils import (
    QueryRegion,
    RegionQueryCache,
    erode_mask,
    farthest_point_sample,
    save_region_cache,
)


EXPERIMENT_ROOT = Path(
    "/data/gaoya/agent-data/outputs/object_query_information_flow_redesign/"
    "latest3350_v1"
)
DEFAULT_OUTPUT_ROOT = (
    EXPERIMENT_ROOT
    / "training_free_m1_direct_enhancement_v2"
    / "test5_20case_5seed"
)
DEFAULT_INPUT_LIST = Path("/data/gaoya/AAA_test_video/0623/testjsons/test_5.txt")
DEFAULT_RANKING = EXPERIMENT_ROOT / "head_scopes_latest3350_with_random100.json"
DEFAULT_SOURCE_TUBES = Path(
    "/data/gaoya/agent-data/outputs/wan_gt_spatiotemporal_correspondence_guidance/"
    "latest3350_top100_cotracker_sam2_v2/gt_tubes"
)
SEEDS = (90094, 68613, 35075, 32466, 13248)
HEIGHT, WIDTH = 704, 1280
POINTS_PER_REGION = 8


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-list", type=Path, default=DEFAULT_INPUT_LIST)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--head-ranking-path", type=Path, default=DEFAULT_RANKING)
    parser.add_argument("--source-tubes-root", type=Path, default=DEFAULT_SOURCE_TUBES)
    parser.add_argument("--overwrite-caches", action="store_true")
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"expected a JSON object: {path}")
    return value


def atomic_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def unique_json_paths(input_list: Path) -> list[Path]:
    paths: list[Path] = []
    seen: set[str] = set()
    for raw in input_list.read_text(encoding="utf-8").splitlines():
        value = raw.strip()
        if not value or value.startswith("#"):
            continue
        path = Path(value).expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(path)
        if path.stem in seen:
            continue
        seen.add(path.stem)
        paths.append(path)
    if len(paths) != 20:
        raise RuntimeError(f"expected 20 unique test_5 cases, got {len(paths)}")
    return paths


def first_frame_rgb(source_video: Path) -> np.ndarray:
    frame = np.asarray(iio.imread(source_video, index=0))
    if frame.ndim != 3 or frame.shape[-1] < 3:
        raise RuntimeError(f"unexpected first frame shape for {source_video}: {frame.shape}")
    frame = frame[..., :3].astype(np.uint8, copy=False)
    return cv2.resize(frame, (WIDTH, HEIGHT), interpolation=cv2.INTER_LANCZOS4)


def build_query_cache(
    *,
    case: str,
    source_json: Path,
    source_video: Path,
    tube_path: Path,
    tube_manifest: dict[str, Any],
    output: Path,
) -> None:
    with np.load(tube_path) as arrays:
        object_points = arrays["query_points_n2"].astype(np.float32)
        object_masks = arrays["masks_othw"][:, 0].astype(np.uint8)
        names = [str(value) for value in arrays["region_names"].tolist()]
        starts = arrays["point_starts"].astype(np.int32)
        ends = arrays["point_ends"].astype(np.int32)
    objects = list(tube_manifest.get("objects") or [])
    if len(objects) != len(names) or len(object_masks) != len(names):
        raise RuntimeError(f"{case}: source tube object metadata mismatch")
    if object_masks.shape[1:] != (HEIGHT, WIDTH):
        raise RuntimeError(f"{case}: expected {HEIGHT}x{WIDTH} tube masks, got {object_masks.shape}")

    regions: list[QueryRegion] = []
    for index, (name, start, end, mask, item) in enumerate(
        zip(names, starts.tolist(), ends.tolist(), object_masks, objects)
    ):
        if name != f"object_{chr(ord('A') + index)}":
            raise RuntimeError(f"{case}: non-canonical object order: {names}")
        if int(end) - int(start) != POINTS_PER_REGION:
            raise RuntimeError(f"{case}/{name}: expected eight query points")
        regions.append(
            QueryRegion(
                region_name=name,
                region_type="object",
                region_phrase=str(item.get("phrase") or name),
                region_slot=index,
                point_start=int(start),
                point_end=int(end),
                mask_area=int(np.asarray(mask, dtype=bool).sum()),
                source_mask_frame=0,
                used_frame_fallback=False,
            )
        )

    union = np.logical_or.reduce(object_masks.astype(bool))
    background = erode_mask(~union, 31)
    border = 32
    background[:border] = False
    background[-border:] = False
    background[:, :border] = False
    background[:, -border:] = False
    background_points = farthest_point_sample(background, POINTS_PER_REGION)
    background_start = len(object_points)
    regions.append(
        QueryRegion(
            region_name="background",
            region_type="background",
            region_phrase=None,
            region_slot=None,
            point_start=background_start,
            point_end=background_start + POINTS_PER_REGION,
            mask_area=int(background.sum()),
            source_mask_frame=0,
            used_frame_fallback=False,
        )
    )
    cache = RegionQueryCache(
        case_key=case,
        query_points=np.concatenate([object_points, background_points], axis=0),
        masks_rhw=np.concatenate(
            [object_masks, background[None].astype(np.uint8)], axis=0
        ),
        regions=regions,
        context_frame_rgb=first_frame_rgb(source_video),
        metadata={
            "case_key": case,
            "query_context_frame": 0,
            "points_per_region": POINTS_PER_REGION,
            "object_count": len(objects),
            "region_count": len(regions),
            "source_json": str(source_json),
            "source_video": str(source_video),
            "height": HEIGHT,
            "width": WIDTH,
            "resize_mode": "stretch",
            "analysis_protocol": "first_pixel_frame_to_first_latent_query",
            "mask_source": "frame-zero slice of the frozen automatic GroundingDINO/SAM2 source tube",
            "query_point_source": "frame-zero automatic object points only",
            "future_source_information_used_by_generation": False,
            "source_tube_protocol": str(tube_manifest.get("protocol")),
            "source_tube_objects": [asdict(region) for region in regions[:-1]],
            "uses_gt_instance_masks": False,
        },
    )
    save_region_cache(output, cache, save_visualizations=True)


def baseline_candidates(output_root: Path, case: str, seed: int) -> list[Path]:
    seed_dir = f"seed_{seed:05d}"
    return [
        Path(
            "/data/gaoya/agent-data/outputs/wan22_ti2v_legacy_firstlatent_pck50/"
            f"runs/{case}/{seed_dir}/generated.mp4"
        ),
        Path(
            "/data/gaoya/agent-data/outputs/"
            "wan22_ti2v_legacy_firstlatent_physiciq67_pck50/"
            f"runs/{case}/{seed_dir}/generated.mp4"
        ),
        Path(
            "/data/gaoya/agent-data/outputs/"
            "wan22_ti2v_legacy_firstlatent_physiciq67_pck50/visual_samples/"
            "attention_zero_seed47326/multicase_multiseed_baselines/"
            f"{case}/{seed_dir}/generated.mp4"
        ),
        output_root / "baselines" / case / seed_dir / "generated.mp4",
    ]


def select_baseline(output_root: Path, case: str, seed: int) -> tuple[Path, bool]:
    candidates = baseline_candidates(output_root, case, seed)
    existing = next(
        (
            path
            for path in candidates[:-1]
            if path.is_file()
            and (path.parent / "manifest.json").is_file()
            and (path.parent / "complete.json").is_file()
        ),
        None,
    )
    return (existing, True) if existing is not None else (candidates[-1], False)


def main() -> None:
    args = parse_args()
    output_root = args.output_root.expanduser().resolve()
    cache_root = output_root / "query_caches_704x1280"
    ranking = read_json(args.head_ranking_path.expanduser().resolve())
    entries = list(ranking.get("entries") or [])
    if len(entries) != 720:
        raise RuntimeError(f"expected 720 ranked physical heads, got {len(entries)}")

    samples: list[dict[str, Any]] = []
    existing_baselines = 0
    cases = unique_json_paths(args.input_list.expanduser().resolve())
    for index, json_path in enumerate(cases, start=1):
        case = json_path.stem
        source_payload = read_json(json_path)
        source_video = Path(str(source_payload["source_video"])).expanduser().resolve()
        if not source_video.is_file():
            raise FileNotFoundError(source_video)
        tube_dir = args.source_tubes_root.expanduser().resolve() / case
        tube_path = tube_dir / "tube.npz"
        tube_manifest_path = tube_dir / "manifest.json"
        if not all(
            path.is_file()
            for path in (tube_path, tube_manifest_path, tube_dir / "complete.json")
        ):
            raise FileNotFoundError(f"{case}: incomplete frozen source tube")
        tube_manifest = read_json(tube_manifest_path)
        cache_dir = cache_root / case
        if args.overwrite_caches or not all(
            (cache_dir / name).is_file()
            for name in ("regions.npz", "regions.json", "complete.json")
        ):
            print(f"[{index}/{len(cases)}] build frame-zero query cache: {case}", flush=True)
            build_query_cache(
                case=case,
                source_json=json_path,
                source_video=source_video,
                tube_path=tube_path,
                tube_manifest=tube_manifest,
                output=cache_dir,
            )
        else:
            print(f"[{index}/{len(cases)}] reuse frame-zero query cache: {case}", flush=True)
        regions_payload = read_json(cache_dir / "regions.json")
        object_regions = [
            item for item in regions_payload["regions"] if item["region_type"] == "object"
        ]
        if not object_regions or object_regions[0]["region_name"] != "object_A":
            raise RuntimeError(f"{case}: object_A is missing from query cache")
        for seed in SEEDS:
            baseline, reused = select_baseline(output_root, case, seed)
            existing_baselines += int(reused)
            samples.append(
                {
                    "case": case,
                    "seed": int(seed),
                    "category": "test_5 Phase-B/D automatic validation",
                    "caption": str(source_payload["input_caption"]),
                    "input_json": str(json_path),
                    "source_video": str(source_video),
                    "query_cache_dir": str(cache_dir),
                    "baseline_video": str(baseline),
                    "baseline_reused_at_manifest_build": bool(reused),
                    "target_region": "object_A",
                    "regions": object_regions,
                }
            )

    manifest = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "experiment_id": "training_free_m1_phase_bd_test5_20case_5seed_v1",
        "input_list": str(args.input_list.expanduser().resolve()),
        "case_count": len(cases),
        "seed_count": len(SEEDS),
        "sample_count": len(samples),
        "seeds": list(SEEDS),
        "target_region": "object_A",
        "head_scope": "latest3350 Top100",
        "head_ranking_path": str(args.head_ranking_path.expanduser().resolve()),
        "completed_runs_at_selection": int(ranking.get("completed_runs_at_selection", 3350)),
        "entries": entries,
        "samples": samples,
        "phase_b": {"alphas": [0.1, 0.25], "denoising_window": [0, 39]},
        "phase_b_selection": {
            "post_generation_only": True,
            "metrics": ["GT full-frame MSE", "GT-relative CoTracker Center-ADE/D0"],
            "aggregation": "seed mean within case; equal case weight; equal-weight within-case ranks",
            "tie_break": "smaller alpha",
        },
        "phase_d": {
            "time_scope": "all_time",
            "denoising_windows": [[0, 9], [0, 19], [0, 39]],
            "full_40_policy": "reuse selected Phase-B video without regeneration",
        },
        "expected": {
            "existing_baselines_at_build": existing_baselines,
            "missing_baselines_at_build": len(samples) - existing_baselines,
            "phase_b_videos": len(samples) * 2,
            "phase_d_new_videos": len(samples) * 2,
            "phase_d_reused_full40_videos": len(samples),
        },
    }
    manifest_path = output_root / "test5_phase_bd_manifest.json"
    atomic_json(manifest_path, manifest)
    atomic_json(
        output_root / "prepare_complete.json",
        {
            "manifest": str(manifest_path),
            "case_count": len(cases),
            "seed_count": len(SEEDS),
            "sample_count": len(samples),
        },
    )
    print(json.dumps(manifest["expected"], ensure_ascii=False, indent=2), flush=True)
    print(manifest_path, flush=True)


if __name__ == "__main__":
    main()
