'use strict';
const $=id=>document.getElementById(id),ctx=$('overlayCanvas').getContext('2d');
const colors={A:'#42df91',B:'#37aef5',C:'#ffae47',D:'#ff514c',estimatedGeometry:'#f453dc',gtGeometry:'#42df91'};
const titles={context:'Context RGB',mask:'Object mask',state:'State p7 / v7',depth:'VGGT depth',geometry:'Collision primitives',rollout:'Bullet rollout'};
const descriptions={context:'原始八帧观察窗口。',mask:'蓝色为 SAM2 区域，黄色为球形轮廓修正。',state:'三维中心重投影；叉号为拟合排除帧。RGB7 箭头表示 v7 × 0.20 s，拟合使用完整八帧。',depth:'暖色近、冷色远。八帧共用色标，低置信度区域更透明。',geometry:'八帧融合静态点图与有限碰撞盒叠加在 RGB7。绿色 GT 仅供评测；地面参数见右侧。',rollout:'未来轨迹叠加于 RGB7 静止背景。A/B/C/D 使用 GT omega。菱形表示首次事件时刻的球心，并非接触点；C aligned 虚线为显式接触对齐结果；BLOCKED 不绘制轨迹。对齐后不再是严格 GT 状态对照。'};
let manifest,data,stage='context',frame=0,playing=false,family='all',ticket=0,images=new Map(),last=0;
const layers={A:true,B:false,C:true,D:true,estimatedGeometry:true,gtGeometry:false};
const fmt=(v,n=3)=>v==null?'N/A':Number(v).toFixed(n),vec=v=>v.map(x=>fmt(x)).join(', ');
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metric=(k,v)=>`<div class="metric-row"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`;
const limit=()=>stage==='rollout'?41:stage==='geometry'?0:7;
const valid=p=>p&&p.every(Number.isFinite);
function list(){const rows=manifest.records.filter(r=>(family==='all'||r.family===family)&&r.case_id.includes($('caseSearch').value));$('visibleCaseCount').textContent=rows.length;$('caseList').innerHTML=rows.map(r=>`<button class="case-row ${data?.case_id===r.case_id?'is-active':''}" role="option" aria-selected="${data?.case_id===r.case_id}" data-case="${esc(r.case_id)}"><strong>${esc(r.case_id.replace('phase1_',''))}</strong><span class="case-ade">${fmt(r.D_ADE_m)}m</span><small>${r.family}</small><small class="${r.D_contact_match?'match':'mismatch'}">${r.D_contact_match?'接触一致':'接触不一致'}</small></button>`).join('');}
async function load(id){const current=++ticket;playing=false;playLabel();$('loadingOverlay').hidden=false;try{const r=await fetch(manifest.records.find(x=>x.case_id===id).data);if(!r.ok)throw Error(r.status);const next=await r.json();const urls=[...next.context.frames,...next.mask.frames,...next.depth.frames,next.geometry.pointmap_frame];const loaded=await Promise.all(urls.map(url=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve([url,im]);im.onerror=()=>reject(Error('图片加载失败 '+url));im.src=url;})));if(current!==ticket)return;data=next;images=new Map(loaded);$('caseTitle').textContent=id.replace('phase1_','');$('familyBadge').textContent=data.family;$('variantText').textContent=`${data.geometry_value} ${data.geometry_units}`;list();selectStage(stage);$('loadingOverlay').hidden=true;}catch(e){$('loadingOverlay').textContent=e.message;console.error(e);}}
function selectStage(s){stage=s;frame=0;playing=false;playLabel();document.querySelectorAll('[data-stage]').forEach(b=>{b.classList.toggle('is-active',b.dataset.stage===s);b.setAttribute('aria-pressed',b.dataset.stage===s);});$('timeline').max=limit();$('timeline').disabled=s==='geometry';$('layerControls').hidden=!['geometry','rollout'].includes(s);document.querySelectorAll('[data-layer]').forEach(i=>i.parentElement.hidden=s==='geometry'&&'ABCD'.includes(i.dataset.layer));inspect();draw();}
function inspect(){if(!data)return;const ev=data.state.evaluation;let rows='';$('inspectorStep').textContent=titles[stage].toUpperCase();$('scopeBadge').textContent=stage==='rollout'?'EVALUATION':'ESTIMATOR';$('scopeBadge').className='scope-badge '+(stage==='rollout'?'evaluation':'estimator');
if(stage==='context')rows=metric('输入','8 × 640 × 360')+metric('观测时长','0.233 s')+metric('已知半径','0.110 m');
if(stage==='mask')rows=metric('身份跟踪','SAM2.1')+metric('修正','球形轮廓')+metric('GT mask','未使用');
if(stage==='state')rows=metric('p7 (m)',vec(data.state.estimated_p7_m))+metric('v7 (m/s)',vec(data.state.estimated_v7_mps))+metric('保留帧',data.state.inlier_frames.join(', '))+metric('评测 |Δp7|',fmt(ev.position_error_m)+' m')+metric('评测 |Δv7|',fmt(ev.vector_error_mps)+' m/s');
if(stage==='depth')rows=metric('色标范围 (m)',data.depth.display_range_m.map(x=>fmt(x,2)).join(' – '))+metric('尺度',fmt(data.depth.metric_scale))+metric('静态点置信度门槛',fmt(data.depth.confidence_threshold));
if(stage==='geometry')rows=metric('Primitive（含地面）',data.geometry.primitive_count)+metric('显示点数',data.geometry.rendered_point_count)+metric('评测中心误差',fmt(data.geometry.evaluation.mean_center_error_m)+' m')+metric('评测尺寸 L2',fmt(data.geometry.evaluation.mean_full_size_l2_error_m)+' m')+metric('地面 z',fmt(data.geometry.ground_fit.ground_top_z_m)+' m');
if(stage==='rollout')rows=Object.entries(data.rollout).map(([k,m])=>metric(k+' ADE / FDE',fmt(m.ADE_m)+' / '+fmt(m.FDE_m)+' m')+(m.status==='PASS'?'':metric(k+' 状态',m.status))+(m.initialization?metric(k+' 初始化',m.initialization.status)+metric(k+' 原穿插',fmt(m.initialization.before_penetration_m*1000)+' mm')+metric(k+' 对齐 Δz',fmt(m.initialization.displacement_m[2]*1000)+' mm')+(m.initialization.reason?metric(k+' 拒绝原因',m.initialization.reason):''):'')).join('')+metric('omega','GT observed · 诊断对照');
$('stageSummary').innerHTML=`<h1>${titles[stage]}</h1><p>${descriptions[stage]}</p><div class="metric-stack">${rows}</div>`;$('boundaryText').textContent=stage==='rollout'?'未来背景固定 RGB7。C aligned 仅竖直对齐已确认支撑面，单列诊断，不混入严格 C 指标。BLOCKED 为初始化拒绝，未推进时间。全部使用 GT omega。':'估计只用 RGB0–7、标定、时间戳、family、已知球半径。GT 误差及绿色几何仅供评测。';}
function line(points,color,width=2,dash=false){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash?[5,4]:[]);ctx.beginPath();let start=true;for(const p of points){if(!valid(p)){start=true;continue;}if(start){ctx.moveTo(...p);start=false;}else ctx.lineTo(...p);}ctx.stroke();ctx.restore();}
function circle(p,r,color){if(!valid(p))return;ctx.beginPath();ctx.arc(...p,r,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();}
function boxes(){for(const p of data.geometry.primitives){if(layers.estimatedGeometry)for(const s of p.estimated_segments)line(s,colors.estimatedGeometry,1.5);if(layers.gtGeometry)for(const s of p.gt_segments)line(s,colors.gtGeometry,1.5,true);}}
function draw(){if(!data)return;let url=data.context.frames[Math.min(frame,7)];if(stage==='mask')url=data.mask.frames[frame];if(stage==='depth')url=data.depth.frames[frame];if(stage==='geometry')url=data.geometry.pointmap_frame;if(stage==='rollout')url=data.context.frames[7];ctx.clearRect(0,0,640,360);ctx.drawImage(images.get(url),0,0,640,360);let keys=[];
if(stage==='mask')keys=[['SAM2','#37aef5'],['Sphere','#ffdc32']];if(stage==='depth')keys=[['近 / near','#f64c32'],['远 / far','#3166db']];
if(stage==='state'){const pts=data.state.centers_px.slice(0,frame+1);line(pts,'#ffdc32');pts.forEach((p,i)=>{circle(p,3,'#ffdc32');if(valid(p)&&data.state.excluded_frames.includes(i)){line([[p[0]-4,p[1]-4],[p[0]+4,p[1]+4]],'#eee');line([[p[0]-4,p[1]+4],[p[0]+4,p[1]-4]],'#eee');}});if(frame===7){const [a,b]=data.state.velocity_arrow_px;line([a,b],'#34e3ec',3);if(valid(a)&&valid(b)){const t=Math.atan2(b[1]-a[1],b[0]-a[0]);line([[b[0]-10*Math.cos(t-.45),b[1]-10*Math.sin(t-.45)],b,[b[0]-10*Math.cos(t+.45),b[1]-10*Math.sin(t+.45)]],'#34e3ec',3);}}keys=[['3D center','#ffdc32'],['v7 × 0.20 s','#34e3ec']];}
if(['geometry','rollout'].includes(stage)){boxes();if(layers.estimatedGeometry)keys.push(['Estimated geometry',colors.estimatedGeometry]);if(layers.gtGeometry)keys.push(['GT · eval only',colors.gtGeometry]);}
if(stage==='rollout')for(const [k,m] of Object.entries(data.rollout)){if(!layers[k])continue;if(!m.points_px.length){keys.push([k+' BLOCKED · 未推进',colors[k]]);continue;}const pts=m.points_px.slice(0,frame+1);line(pts,'#111',4);line(pts,colors[k],2,m.initialization?.status==='CONTACT_ALIGNED'||m.status!=='PASS');circle(m.points_px[frame],m.radius_px[frame],colors[k]);const ei=m.first_contact_path_index;if(ei!=null&&frame>=ei&&valid(m.points_px[ei])){const [x,y]=m.points_px[ei];line([[x,y-6],[x+6,y],[x,y+6],[x-6,y],[x,y-6]],colors[k]);}keys.push([k+(m.initialization?.status==='CONTACT_ALIGNED'?' aligned':m.status==='PASS'?'':' INVALID'),colors[k]]);}
$('canvasKey').innerHTML=keys.map(([n,c])=>`<span class="key-item"><i class="key-dot" style="color:${c}"></i>${esc(n)}</span>`).join('');const rgb=stage==='rollout'?frame+7:stage==='geometry'?7:frame;$('frameBadge').textContent=`RGB${rgb}${stage==='rollout'?' · RGB7 HOLD':''}`;$('timeline').value=frame;$('timeOutput').textContent=(stage==='rollout'?'+':'')+fmt((stage==='geometry'?7:frame)/30)+' s';let values=[['帧','RGB'+rgb]];
if(stage==='mask')values.push(['SAM2 面积',data.mask.sam2_area_pixels[frame]+' px'],['球形面积',data.mask.sphere_area_pixels[frame]+' px']);if(stage==='state')values.push(['3D center (m)',vec(data.state.centers_world_m[frame])]);if(stage==='rollout')for(const [k,m] of Object.entries(data.rollout))if(layers[k])values.push([k+' 位置误差',frame?fmt(m.position_error_m[frame-1])+' m':'初始化'],[k+' 首次事件',m.first_contact_time_s==null?'无':fmt(m.first_contact_time_s)+' s'],[k+' 接触结果',m.contact_outcome],[k+' 最大穿透',m.max_penetration_m==null?'NOT_RUN':fmt(m.max_penetration_m*1000)+' mm']);$('frameReadout').innerHTML=values.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');}
function playLabel(){$('playPause').textContent=playing?'Ⅱ':'▶';$('playPause').setAttribute('aria-label',playing?'暂停':'播放');}
function tick(now){if(playing&&now-last>=1000/Number($('playbackFps').value)){last=now;frame=(frame+1)%(limit()+1);draw();}requestAnimationFrame(tick);}
$('playPause').onclick=()=>{if(!data||stage==='geometry')return;playing=!playing;last=performance.now();playLabel();};$('previousFrame').onclick=()=>{frame=Math.max(0,frame-1);draw();};$('nextFrame').onclick=()=>{frame=Math.min(limit(),frame+1);draw();};$('timeline').oninput=e=>{frame=Number(e.target.value);playing=false;playLabel();draw();};$('caseSearch').oninput=list;$('caseList').onclick=e=>{const b=e.target.closest('[data-case]');if(b)load(b.dataset.case);};
document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{family=b.dataset.family;document.querySelectorAll('[data-family]').forEach(x=>x.classList.toggle('is-active',x===b));list();});document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>selectStage(b.dataset.stage));document.querySelectorAll('[data-layer]').forEach(i=>i.onchange=()=>{layers[i.dataset.layer]=i.checked;draw();});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('playPause').click();}if(e.code==='ArrowRight')$('nextFrame').click();if(e.code==='ArrowLeft')$('previousFrame').click();});
(async()=>{try{const r=await fetch('data/manifest.json');if(!r.ok)throw Error(r.status);manifest=await r.json();$('summaryAde').textContent=fmt(manifest.summary.D_ADE_m)+'m';$('summaryFde').textContent=fmt(manifest.summary.D_FDE_m)+'m';$('summaryContact').textContent=manifest.summary.D_contact_match+'/36';list();await load(manifest.default_case_id);requestAnimationFrame(tick);}catch(e){$('loadingOverlay').textContent='加载失败 '+e.message;console.error(e);}})();

